// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjektPrzelicznik.Context;

namespace ProjektPrzelicznik.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220329074745_migracja")]
    partial class migracja
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ProjektPrzelicznik.Model.Jednostki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int>("RodzajeJednostekId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RodzajeJednostekId");

                    b.ToTable("Jednostki");
                });

            modelBuilder.Entity("ProjektPrzelicznik.Model.Przelicznik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkiDocelowejId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JednostkiZrodloweId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Mnoznik")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("JednostkiDocelowejId");

                    b.HasIndex("JednostkiZrodloweId");

                    b.ToTable("Przelicznik");
                });

            modelBuilder.Entity("ProjektPrzelicznik.Model.Rodzaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rodzaj");
                });

            modelBuilder.Entity("ProjektPrzelicznik.Model.Jednostki", b =>
                {
                    b.HasOne("ProjektPrzelicznik.Model.Rodzaj", "RodzajeJednostek")
                        .WithMany()
                        .HasForeignKey("RodzajeJednostekId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RodzajeJednostek");
                });

            modelBuilder.Entity("ProjektPrzelicznik.Model.Przelicznik", b =>
                {
                    b.HasOne("ProjektPrzelicznik.Model.Jednostki", "JednostkiDocelowej")
                        .WithMany()
                        .HasForeignKey("JednostkiDocelowejId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjektPrzelicznik.Model.Jednostki", "JednostkiZrodlowe")
                        .WithMany()
                        .HasForeignKey("JednostkiZrodloweId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JednostkiDocelowej");

                    b.Navigation("JednostkiZrodlowe");
                });
#pragma warning restore 612, 618
        }
    }
}
